// AI Perfumery Engine; ownership follows the owner's existing agreement. No new licence granted.
'use client';
import {useEffect, useState} from 'react';
import type {Ingredient, FormulaVersion, Formula} from '../lib/model';
import {appendVersion, demoRegulation, downloadDemo, familyShares, findings, materials, rows} from '../lib/model';
import {validateDemoContext as validateContext} from '../lib/formula-validation';
export {validateDemoDeclaration} from '../lib/formula-validation';
import {useDemo} from '../lib/demo-context';
import {Badge, EmptyState, Icon, Modal, Notice, PageHeader, Panel} from './ui';
import './formula-pages.css';
import {Dropdown} from './dropdown';

function cloneVersion(version:FormulaVersion):FormulaVersion {return {...version,ingredients:version.ingredients.map(item=>({...item}))};}
function freshDraft():FormulaVersion {
  return {id:'draft',number:1,createdLabel:'This session',note:'Initial demo version',vehicle:'Demo vehicle A',category:'Demo application A',dilution:'20',ingredients:[{id:'new-row-1',materialId:materials[0].id,amount:'100'}]};
}
type DraftFieldsProps={draft:FormulaVersion;onChange:(draft:FormulaVersion)=>void;readOnly?:boolean;prefix:string};
function ContextFields({draft,onChange,readOnly=false,prefix}:DraftFieldsProps) {
  return <div className="formula-context">
    <div className="field"><label className="field-label" htmlFor={`${prefix}-vehicle`}>Vehicle</label><Dropdown className="select" aria-label="Vehicle" id={`${prefix}-vehicle`} value={draft.vehicle} disabled={readOnly} onValueChange={value=>onChange({...draft,vehicle:value})}><option>Ethanol 96% (hydroalcoholic)</option><option>Dipropylene glycol (DPG)</option></Dropdown><span className="small muted">Synthetic hydroalcoholic context</span></div>
    <div className="field"><label className="field-label" htmlFor={`${prefix}-application`}>Application</label><Dropdown className="select" aria-label="Application" id={`${prefix}-application`} value={draft.category} disabled={readOnly} onValueChange={value=>onChange({...draft,category:value})}><option>Demo category 4</option><option>Demo category 5A</option></Dropdown><span className="small muted">Stands in for an IFRA product category; the real list is not loaded</span></div>
    <div className="field"><label className="field-label" htmlFor={`${prefix}-dilution`}>Product dilution</label><div className="formula-input-unit"><input className="input" id={`${prefix}-dilution`} inputMode="decimal" value={draft.dilution} disabled={readOnly} onChange={e=>onChange({...draft,dilution:e.target.value})}/><span>%</span></div><span className="small muted">Declared input · no hidden default</span></div>
  </div>;
}
function IngredientFields({draft,onChange,readOnly=false,prefix}:DraftFieldsProps) {
  const [batch,setBatch]=useState('');
  const unused=materials.filter(m=>!draft.ingredients.some(i=>i.materialId===m.id));
  const replace=(id:string,patch:Partial<Ingredient>)=>onChange({...draft,ingredients:draft.ingredients.map(item=>item.id===id?{...item,...patch}:item)});
  const computed=rows(draft,batch);
  return <>
    <div className="formula-table-footer"><span className="small muted">A formula is declared in weight percent and must total exactly 100%. Grams appear once you declare a batch size, because a mass needs a target to be a mass (FR-004).</span><div className="field"><label className="field-label" htmlFor={`${prefix}-batch`}>Batch size</label><div className="formula-input-unit"><input className="input formula-amount-input" id={`${prefix}-batch`} inputMode="decimal" placeholder="e.g. 50" value={batch} onChange={e=>setBatch(e.target.value)}/><span>g</span></div></div></div>
    <div className="table-wrap"><table className="data-table formula-ingredient-table"><caption className="sr-only">Declared materials. Amounts are weight percentages of the concentrate; the remaining columns are computed from them.</caption><thead><tr><th scope="col">Material</th><th scope="col">Family</th><th scope="col">Declared w/w</th><th scope="col">% of product</th>{batch&&<th scope="col">Mass</th>}{!readOnly&&<th scope="col"><span className="sr-only">Remove row</span></th>}</tr></thead><tbody>{computed.map((row,index)=>{
      const item=row.item, material=row.material;
      return <tr key={item.id}>
        <td><div className="formula-material-cell"><span className="formula-material-dot" style={{background:material?.color}}/><div>{readOnly?<strong>{material?.name||'Unknown material'}</strong>:<><label className="sr-only" htmlFor={`${prefix}-material-${item.id}`}>Material for row {index+1}</label><Dropdown className="formula-material-select" aria-label={`Material for row ${index+1}`} id={`${prefix}-material-${item.id}`} value={item.materialId} onValueChange={value=>replace(item.id,{materialId:value})}>{materials.filter(m=>m.id===item.materialId||!draft.ingredients.some(i=>i.materialId===m.id)).map(m=><option value={m.id} key={m.id}>{m.name}</option>)}</Dropdown></>}<span className="formula-material-id small muted">CAS {material?.cas}</span></div></div></td>
        <td><span className="formula-family">{material?.family}</span></td>
        <td>{readOnly?<span className="formula-amount">{item.amount}%</span>:<div className="formula-input-unit formula-amount-input"><label className="sr-only" htmlFor={`${prefix}-amount-${item.id}`}>Declared percentage for row {index+1}</label><input className="input" id={`${prefix}-amount-${item.id}`} inputMode="decimal" value={item.amount} onChange={e=>replace(item.id,{amount:e.target.value})}/><span>%</span></div>}</td>
        <td className="formula-amount">{row.pctInProduct??<span className="muted">—</span>}</td>
        {batch&&<td className="formula-amount">{row.massInBatch?`${row.massInBatch} g`:<span className="muted">—</span>}</td>}
        {!readOnly&&<td><button className="icon-button formula-remove" aria-label={`Remove row ${index+1}`} onClick={()=>onChange({...draft,ingredients:draft.ingredients.filter(x=>x.id!==item.id)})}><Icon name="close" size={16}/></button></td>}
      </tr>;
    })}</tbody></table></div>
    <div className="formula-table-footer"><span className="small muted">Decimal declarations stay as entered. No automatic normalisation. The product column applies the declared dilution once.</span>{!readOnly&&<button className="button ghost" disabled={!unused.length} onClick={()=>{if(unused[0])onChange({...draft,ingredients:[...draft.ingredients,{id:`row-${Date.now()}`,materialId:unused[0].id,amount:'0'}]});}}><Icon name="plus" size={16}/>Add material</button>}</div>
  </>;
}

export function FormulaLibrary() {
  const {formulas,setFormulas,selectFormula,navigate,t,notify,setDirty}=useDemo();
  const [query,setQuery]=useState('');
  const [filter,setFilter]=useState('all');
  const [creating,setCreating]=useState(false);
  const [name,setName]=useState('');
  const [draft,setDraft]=useState<FormulaVersion>(freshDraft);
  const [error,setError]=useState('');
  const write=true;
  const filtered=formulas.filter(formula=>(`${formula.name} ${formula.code}`).toLowerCase().includes(query.toLowerCase())&&(filter!=='multiple'||formula.versions.length>1));
  const close=()=>{setCreating(false);setDirty(false);setError('');};
  const create=()=>{
    const problem=!name.trim()?'Enter a name for this demo formula.':validateContext(draft);
    if(problem){setError(problem);return;}
    const id=`formula-demo-${Date.now()}`;
    const next:Formula={id,name:name.trim(),code:`F-${String(formulas.length+1).padStart(3,'0')}`,updatedLabel:'Just now',versions:[{...cloneVersion(draft),id:`${id}-v1`,number:1,note:'Initial synthetic version'}]};
    setFormulas(items=>[next,...items]);close();selectFormula(id);navigate('editor');notify(t('New synthetic formula created.','สร้างสูตรจำลองแล้ว'));
  };
  return <>
    <PageHeader eyebrow="YOUR WORKSPACE" title={t('Formula library','คลังสูตร')} description={t('Your studies, saved as immutable versions.','จัดการสูตรและเวอร์ชันที่บันทึกไว้')} actions={write&&<button className="button primary" onClick={()=>{setName('');setDraft(freshDraft());setCreating(true);}}><Icon name="plus" size={18}/>{t('New formula','สร้างสูตร')}</button>}/>
    <div className="formula-library-summary"><div><span className="formula-summary-value">{formulas.length}</span><span className="muted">Synthetic formulas</span></div><div><span className="formula-summary-value">{formulas.reduce((sum,x)=>sum+x.versions.length,0)}</span><span className="muted">Immutable snapshots</span></div><div><Badge tone="purple">Demo workspace</Badge><span className="muted">Session only · resets on reload</span></div></div>
    <Panel className="formula-library-panel"><div className="formula-library-toolbar"><div className="formula-search"><Icon name="search" size={19}/><label htmlFor="formula-search" className="sr-only">Search formulas</label><input className="input" id="formula-search" type="search" placeholder={t('Search name or formula code…','ค้นหาชื่อหรือรหัสสูตร…')} value={query} onChange={e=>setQuery(e.target.value)}/></div><label className="sr-only" htmlFor="formula-library-filter">Filter formulas</label><Dropdown id="formula-library-filter" aria-label="Filter formulas" className="select" value={filter} onValueChange={value=>setFilter(value)}><option value="all">All formulas</option><option value="multiple">Multiple versions</option></Dropdown></div>
    {filtered.length?<div className="table-wrap"><table className="data-table formula-library-table"><caption className="sr-only">Saved synthetic formulas</caption><thead><tr><th scope="col">Formula</th><th scope="col">Latest version</th><th scope="col">Materials</th><th scope="col">Updated</th><th scope="col"><span className="sr-only">Open</span></th></tr></thead><tbody>{filtered.map(formula=>{const latest=formula.versions[formula.versions.length-1];return <tr key={formula.id}><td><button className="formula-title-link" onClick={()=>{selectFormula(formula.id);navigate('editor');}}>{formula.name}</button><span className="small muted formula-material-id">{formula.code} · Synthetic study</span></td><td><Badge tone="purple">v{latest.number}</Badge><span className="small muted formula-version-count">{formula.versions.length} snapshots</span></td><td>{latest.ingredients.length}</td><td className="muted">{formula.updatedLabel}</td><td><button className="button ghost" aria-label={`Open ${formula.name}`} onClick={()=>{selectFormula(formula.id);navigate('editor');}}>Open<Icon name="arrow" size={17}/></button></td></tr>;})}</tbody></table></div>:<EmptyState title={t('No matching formulas','ไม่พบสูตร')} description={t('Try another search or show all formulas.','ลองค้นหาใหม่หรือแสดงสูตรทั้งหมด')} action={<button className="button secondary" onClick={()=>{setQuery('');setFilter('all');}}>Clear filters</button>}/>}
    </Panel><p className="small muted formula-bottom-note">Every material, formula and identity in this demo is invented. No owner dataset is included.</p>
    <Modal open={creating} onClose={close} title={t('Create a demo formula','สร้างสูตรจำลอง')}><div className="stack"><Notice>Use invented names and materials only. This demo stores changes in memory, for this session.</Notice><div className="field"><label className="field-label" htmlFor="new-formula-name">Formula name</label><input className="input" id="new-formula-name" value={name} placeholder="e.g. Evening Study" maxLength={100} onChange={e=>{setName(e.target.value);setDirty(true);}}/></div><ContextFields draft={draft} prefix="new" onChange={value=>{setDraft(value);setDirty(true);}}/><IngredientFields draft={draft} prefix="new" onChange={value=>{setDraft(value);setDirty(true);}}/>{error&&<div role="alert"><Notice tone="red">{error}</Notice></div>}<div className="formula-modal-actions"><button className="button secondary" onClick={close}>{t('Cancel','ยกเลิก')}</button><button className="button primary" onClick={create}>{t('Create formula','สร้างสูตร')}</button></div></div></Modal>
  </>;
}

function CompositionChart({draft}:{draft:FormulaVersion}) {
  const shares=familyShares(draft);
  const [table,setTable]=useState(false);
  return <><div className="formula-chart-title"><div><h3>Composition by odour family</h3><p className="small muted">Share of the concentrate by weight · computed from your declared amounts</p></div><button className="button ghost" onClick={()=>setTable(!table)} aria-expanded={table}>{table?'Hide data':'View data'}</button></div>
  {shares.length===0?<EmptyState title="No materials declared" description="Add a material to see its family share."/>:table?<table className="data-table"><caption>Declared share by odour family, in weight percent of the concentrate.</caption><thead><tr><th>Odour family</th><th>Share of concentrate</th></tr></thead><tbody>{shares.map(row=><tr key={row.family}><td>{row.family}</td><td>{row.pct}%</td></tr>)}</tbody></table>:<div className="formula-profile-chart" role="img" aria-label="Composition by odour family, in weight percent of the concentrate.">{shares.map(row=><div className="formula-profile-row" key={row.family}><span>{row.family}</span><div className="formula-bar-track"><span style={{width:`${Math.min(row.pct,100)}%`,background:row.color}}/></div><span className="muted">{row.pct}%</span></div>)}</div>}
  <div className="formula-chart-caption"><span className="formula-chart-dot"/>Weighting: composition share by mass. Not perceived strength.</div></>;
}
function CompliancePanel({draft}:{draft:FormulaVersion}) {
  const list=findings(draft,'');
  return <><div className="formula-chart-title"><div><h3>Restriction findings</h3><p className="small muted">Finished-product share compared against a declared limit</p></div></div>
  <Notice tone="amber">{demoRegulation.note} The real rows come from the supplied IFRA Standards extract, which is not in this repository and has not been extracted yet. Two materials below carry a fictional limit so the states can be seen; the rest answer honestly.</Notice>
  <div className="table-wrap"><table className="data-table"><caption className="sr-only">Restriction findings per material.</caption><thead><tr><th scope="col">Material</th><th scope="col">% of product</th><th scope="col">Limit</th><th scope="col">Finding</th></tr></thead><tbody>{list.map(f=><tr key={f.row.item.id}><td><strong>{f.row.material?.name}</strong><span className="formula-material-id small muted">CAS {f.row.material?.cas}</span></td><td className="formula-amount">{f.row.pctInProduct??'—'}</td><td className="formula-amount">{f.limit?`${f.limit}%`:'—'}</td><td>{f.status==='within'?<Badge tone="green">Within limit</Badge>:f.status==='over'?<Badge tone="red">Over limit</Badge>:<Badge tone="amber">Insufficient data</Badge>}{f.locator&&<span className="formula-material-id small muted">{f.locator}</span>}{f.missing&&<span className="formula-material-id small muted">{f.missing}</span>}</td></tr>)}</tbody></table></div></>;
}
function EvolutionPanel({draft}:{draft:FormulaVersion}) {
  const list=rows(draft,'');
  return <><div className="formula-chart-title"><div><h3>Evolution over time</h3><p className="small muted">One row per material in this formula</p></div></div>
  <Notice tone="amber">No curve is drawn. The evaporation model, its mixture assumption, and the surface-area and airflow assumptions the dataset does not supply are all undecided (decision 4), and the detection threshold each curve would be scaled against is empty in the supplied sample. A plausible-looking curve here would be a guess.</Notice>
  <div className="table-wrap"><table className="data-table"><caption className="sr-only">Per-material evolution state.</caption><thead><tr><th scope="col">Material</th><th scope="col">Share of concentrate</th><th scope="col">Predicted intensity over time</th></tr></thead><tbody>{list.map(row=><tr key={row.item.id}><td><strong>{row.material?.name}</strong><span className="formula-material-id small muted">CAS {row.material?.cas}</span></td><td className="formula-amount">{row.pctInFormula}%</td><td><Badge tone="amber">Insufficient data</Badge><span className="formula-material-id small muted">No approved model</span></td></tr>)}</tbody></table></div></>;
}
type AnalysisTab='overview'|'composition'|'compliance'|'evolution'|'error-budget'|'provenance';
function AnalysisPanels({draft,formula,fixture,stale,onShowFixture}:{draft:FormulaVersion;formula:Formula;fixture:boolean;stale:boolean;onShowFixture:()=>void}) {
  const [tab,setTab]=useState<AnalysisTab>('overview');
  const [tree,setTree]=useState(false);
  return <Panel className="formula-analysis"><div className="panel-heading formula-analysis-heading"><div><span className="eyebrow">UNDERSTAND THE RESULT</span><h2>Analysis workspace</h2></div><Badge tone="purple">Declared values only</Badge></div><div className="tabs formula-analysis-tabs" aria-label="Analysis views">{([['overview','Overview'],['composition','Composition'],['compliance','Restrictions'],['evolution','Evolution'],['error-budget','Error budget'],['provenance','Provenance']] as [AnalysisTab,string][]).map(([value,label])=><button className={`tab ${tab===value?'active':''}`} key={value} aria-pressed={tab===value} onClick={()=>setTab(value)}>{label}</button>)}</div><div className="formula-analysis-content">
    {fixture&&<div className="formula-fixture-strip"><Icon name="info" size={17}/><span>Hand-authored screen illustration. It is independent of your inputs and provides no chemical, safety or performance prediction.{stale?' Current inputs have changed.':''}</span></div>}
    {tab==='provenance'?<><div className="formula-chart-title"><div><h3>Evidence and missing inputs</h3><p className="small muted">Every input and every gap stays visible.</p></div><button className="button secondary" onClick={()=>setTree(!tree)}>{tree?'List view':'Tree view'}</button></div><div className={tree?'formula-provenance-tree':'formula-provenance-list'}><div><Icon name="layers" size={18}/><span><strong>Input snapshot</strong><br/><code>{formula.code} / {draft.id}</code><br/><span className="small muted">Declared decimal strings, vehicle, category and product dilution, exactly as entered.</span></span></div><div><Icon name="file" size={18}/><span><strong>Composition and finished-product share</strong><br/><span className="small muted">Arithmetic on the declared percentages. No model, no measurement, no approval needed.</span></span></div><div><Icon name="shield" size={18}/><span><strong>{demoRegulation.label}</strong><br/><span className="small muted">{demoRegulation.note} Real rows come from the supplied IFRA Standards extract, which is not in this repository and has not been extracted yet.</span></span></div><div><Icon name="alert" size={18}/><span><strong>Missing: evaporation model</strong><br/><span className="small muted">No equation, mixture assumption, surface area or airflow is approved, so no curve can be drawn (decision 4).</span></span></div><div><Icon name="alert" size={18}/><span><strong>Missing: perception weighting</strong><br/><span className="small muted">Detection thresholds are absent from the supplied sample and categorical strength has no numeric mapping, so composition share is the only honest weighting today.</span></span></div></div></>:tab==='error-budget'?<><h3>Error budget</h3><Notice tone="amber">Unquantified. An uncertainty policy and supporting measurements are required before intervals or contributor percentages can be reported.</Notice><div className="formula-missing-grid"><div><span>Model uncertainty</span><Badge tone="amber">No data</Badge></div><div><span>Observation uncertainty</span><Badge tone="amber">Not measured</Badge></div><div><span>Calibration evidence</span><Badge tone="amber">Needs calibration</Badge></div><div><span>Contributor shares</span><Badge tone="amber">Unquantified</Badge></div></div></>:tab==='composition'?<CompositionChart draft={draft}/>:tab==='compliance'?<CompliancePanel draft={draft}/>:tab==='evolution'?<EvolutionPanel draft={draft}/>:<div className="formula-chart-grid"><div><CompositionChart draft={draft}/></div><div><CompliancePanel draft={draft}/></div></div>}
  </div></Panel>;
}

export function FormulaEditor() {
  const {formulas,setFormulas,selectedId,t,navigate,notify,setDirty,dirty}=useDemo();
  const formula=formulas.find(x=>x.id===selectedId)||formulas[0];
  const latest=formula?.versions[formula.versions.length-1];
  const [versionId,setVersionId]=useState(latest?.id||'');
  const saved=formula?.versions.find(version=>version.id===versionId)||latest;
  const [draft,setDraft]=useState<FormulaVersion>(()=>cloneVersion(latest||freshDraft()));
  const [trial,setTrial]=useState(false);
  const [fixture,setFixture]=useState(true);
  const [evaluated,setEvaluated]=useState(false);
  const [saveOpen,setSaveOpen]=useState(false);
  const [note,setNote]=useState('');
  const [error,setError]=useState('');
  const [pendingVersion,setPendingVersion]=useState('');
  const [modelChanged,setModelChanged]=useState(false);
  const [historyOpen,setHistoryOpen]=useState(false);
  const writer=true;
  const reader=true;
  const historical=saved?.id!==latest?.id;
  const readOnly=trial?!reader:(!writer||historical);
  if(!formula||!saved) return <EmptyState title="No formula selected" description="Choose a synthetic formula to open the workspace." action={<button className="button primary" onClick={()=>navigate('formulas')}>Open library</button>}/>;
  const change=(value:FormulaVersion)=>{if(readOnly)return;setDraft(value);setDirty(true);setEvaluated(false);};
  const discard=()=>{setDraft(cloneVersion(saved));setDirty(false);setTrial(false);setError('');setEvaluated(false);setFixture(true);notify('Unsaved input discarded. The saved snapshot is unchanged.');};
  const switchVersion=(id:string)=>{const next=formula.versions.find(x=>x.id===id);if(!next)return;setVersionId(id);setDraft(cloneVersion(next));setDirty(false);setTrial(false);setFixture(true);setEvaluated(false);setError('');setPendingVersion('');};
  const startTrial=()=>{if(!reader)return;setDraft(cloneVersion(saved));setTrial(true);setDirty(false);setEvaluated(false);setFixture(false);notify('What-if started. Trial input is transient until you explicitly save a new version.');};
  const evaluate=()=>{const problem=validateContext(draft);setError(problem||'');setFixture(false);setEvaluated(true);notify(problem?'Review the highlighted input error.':'Evaluation: insufficient data. No scientific output has been fabricated.');};
  const beginSave=()=>{if(!writer)return;const problem=validateContext(draft);if(problem){setError(problem);return;}setError('');setNote('');setSaveOpen(true);};
  const save=()=>{if(!note.trim()){setError('Add a version note explaining this synthetic change.');return;}const problem=validateContext(draft);if(problem){setError(problem);return;}const next=appendVersion(formula,draft,note.trim());const version=next.versions[next.versions.length-1];setFormulas(items=>items.map(item=>item.id===formula.id?next:item));setVersionId(version.id);setDraft(cloneVersion(version));setSaveOpen(false);setDirty(false);setTrial(false);setEvaluated(false);setFixture(false);setError('');notify(`Saved ${formula.code} v${version.number}. Earlier snapshots remain unchanged.`);};
  return <>
    <div className="formula-breadcrumb"><button className="button ghost" onClick={()=>navigate('formulas')}><Icon name="back" size={17}/>{t('Formula library','คลังสูตร')}</button><span>/</span><span>{formula.code}</span></div>
    <PageHeader eyebrow="FORMULA WORKSPACE" title={formula.name} description={t('A careful space to formulate, experiment and understand.','พื้นที่สร้างสูตร ทดลอง และตรวจสอบผล')} actions={<button className="button secondary" onClick={()=>downloadDemo(`${formula.code}-v${saved.number}-synthetic.json`,{demo:true,warning:'Synthetic demonstration only. No scientific or regulatory result.',formulaCode:formula.code,formulaName:formula.name,snapshot:saved,analysis:{status:'insufficient_data',missing:['approved models','uncertainty policy','source rules']}})}><Icon name="download" size={17}/>{t('Export snapshot','ส่งออกข้อมูลจำลอง')}</button>}/>
    <div className="formula-status-bar"><div className="row"><Badge tone={dirty?'amber':'purple'}>{dirty?(trial?'Unsaved what-if':'Unsaved changes'):`Saved v${saved.number}`}</Badge><Badge>Synthetic data</Badge>{historical&&<Badge>Historical snapshot</Badge>}</div><div className="formula-version-picker"><label htmlFor="formula-version">Version</label><Dropdown id="formula-version" aria-label="Version" className="select" value={saved.id} onValueChange={value=>dirty?setPendingVersion(value):switchVersion(value)}>{[...formula.versions].reverse().map(version=><option value={version.id} key={version.id}>v{version.number}{version.id===latest?.id?' · Latest':''}</option>)}</Dropdown><button className="button ghost" onClick={()=>setHistoryOpen(!historyOpen)} aria-expanded={historyOpen}><Icon name="clock" size={17}/>History</button></div></div>
    {historyOpen&&<Panel className="formula-history"><div className="panel-heading"><h2>Immutable version history</h2><span className="small muted">Select a snapshot to view</span></div>{[...formula.versions].reverse().map(version=><button key={version.id} className={`formula-history-item ${version.id===saved.id?'selected':''}`} onClick={()=>dirty?setPendingVersion(version.id):switchVersion(version.id)}><span className="formula-history-version">v{version.number}</span><span><strong>{version.note}</strong><br/><span className="small muted">{version.createdLabel}</span></span><Icon name="arrow" size={17}/></button>)}</Panel>}
    <Panel className="formula-context-panel"><ContextFields draft={draft} prefix="editor" onChange={change} readOnly={readOnly}/></Panel>
    <div className="formula-freshness"><span><i className={dirty?'changed':''}/><strong>Input:</strong> {dirty?'changed since saved snapshot':'saved snapshot selected'}</span><span><i className={modelChanged?'changed':''}/><strong>Model:</strong> {modelChanged?'fixture revision changed':'no approved model'}</span><button className="button ghost" onClick={()=>{setModelChanged(!modelChanged);setFixture(false);setEvaluated(false);notify('Model-change scenario toggled. This changes only a demonstration status, not your formula.');}}>Try model-change state</button></div>
    {trial&&<Notice tone="amber"><strong>What-if workspace.</strong> Changes are temporary. Evaluate does not save them; saving creates a separate immutable version.</Notice>}
    {error&&!saveOpen&&<div role="alert"><Notice tone="red">{error}</Notice></div>}
    <div className="formula-workspace-grid"><Panel className="formula-material-panel"><div className="panel-heading"><div><h2>{t('Material composition','ส่วนประกอบสูตร')}</h2><p className="small muted">Declared formula percentages · w/w</p></div><Badge>{draft.ingredients.length} materials</Badge></div><IngredientFields draft={draft} prefix="editor" onChange={change} readOnly={readOnly}/><div className="formula-editor-actions"><div>{!readOnly&&<button className="button secondary" onClick={discard} disabled={!dirty&&!trial}>{t('Discard','ยกเลิกการเปลี่ยนแปลง')}</button>}{reader&&!trial&&<button className="button secondary" onClick={startTrial} disabled={dirty}>{t('Start what-if','เริ่มทดลองแบบ What-if')}</button>}</div><div><button className="button secondary" onClick={evaluate}><Icon name="chart" size={17}/>{t('Evaluate','ประเมินผล')}</button>{writer&&(!historical||trial)&&<button className="button primary" onClick={beginSave} disabled={!dirty}><Icon name="check" size={17}/>{t('Save new version','บันทึกเวอร์ชันใหม่')}</button>}</div></div>{historical&&!trial&&<p className="small muted formula-readonly-note">Historical snapshots are read only. Start a what-if to try temporary changes.</p>}</Panel>
    <Panel className="formula-evidence-panel"><div className="formula-evidence-heading"><span className="formula-evidence-icon"><Icon name="spark" size={21}/></span><h2>{t('Why this result','เหตุผลของผลลัพธ์')}</h2></div><Badge tone="amber">Insufficient data</Badge><p>No approved chemistry is included in this demonstration.</p><div className="formula-evidence-items"><div><Icon name="layers" size={18}/><span><strong>Input snapshot</strong><span>{formula.code} · v{saved.number}{dirty?' + unsaved input':''}</span></span></div><div><Icon name="book" size={18}/><span><strong>Model evidence</strong><span>Missing profile definitions and physical models.</span></span></div><div><Icon name="shield" size={18}/><span><strong>Rule evidence</strong><span>No approved interaction or regulatory rules.</span></span></div></div><div className="formula-evidence-foot">{evaluated?'Input was checked. Scientific evaluation stopped at missing evidence.':'Evaluation returns missing-data reasons, never guessed predictions.'}</div></Panel></div>
    <Panel className="formula-interactions"><div className="formula-check-icon"><Icon name="alert" size={20}/></div><div><h3>Material groups and pair checks are not designed</h3><p className="small muted">Synergy, masking and material-group checks were in the original product idea. The supplied data has no group or pair field, no table defines them, and no engine output computes them (data-model.md 4, decision 11). Until the owner defines them, a pair with no rule must answer insufficient data rather than a guess.</p></div><Badge tone="amber">Not designed</Badge></Panel>
    <AnalysisPanels draft={draft} formula={formula} fixture={fixture} stale={dirty||modelChanged} onShowFixture={()=>setFixture(true)}/>
    <Modal open={saveOpen} onClose={()=>{setSaveOpen(false);setError('');}} title={t('Save an immutable version','บันทึกเวอร์ชันใหม่')}><div className="stack"><Notice>Creates v{Math.max(...formula.versions.map(x=>x.number))+1}. Existing snapshots remain unchanged. This saves demo input, without scientific validation.</Notice><div className="field"><label htmlFor="version-note" className="field-label">Version note</label><textarea className="input" id="version-note" rows={3} maxLength={240} placeholder="Describe this synthetic formulation change…" value={note} onChange={e=>setNote(e.target.value)}/></div>{error&&<div role="alert"><Notice tone="red">{error}</Notice></div>}<div className="formula-modal-actions"><button className="button secondary" onClick={()=>{setSaveOpen(false);setError('');}}>Cancel</button><button className="button primary" onClick={save}>Save v{Math.max(...formula.versions.map(x=>x.number))+1}</button></div></div></Modal>
    <Modal open={!!pendingVersion} onClose={()=>setPendingVersion('')} title="Discard unsaved input?"><div className="stack"><p>Switching snapshots will discard your unsaved {trial?'what-if':'formula'} input. Saved versions remain unchanged.</p><div className="formula-modal-actions"><button className="button secondary" onClick={()=>setPendingVersion('')}>Keep editing</button><button className="button danger" onClick={()=>switchVersion(pendingVersion)}>Discard and switch</button></div></div></Modal>
  </>;
}
